### ISSUE TITLE
sonar-plugin is deprecated as of gradle 2.8

### ISSUE THREAD

**Issue by harningt** [ajoberstar/gradle-defaults#10]
The sonar-plugin is deprecated as of gradle 2.8 and will be removed in gradle 3.0.
A replacement is released from SonarQube: http://docs.sonarqube.org/display/SONAR/Analyzing+with+SonarQube+Scanner+for+Gradle

Perhaps a configuration option to forcefully disable certain plugins from being included would be a useful intermediary in case integrating the plugin is problematic.

Current effect in gradle is a warning display on every execution:
`The 'sonar-runner' plugin has been deprecated and is scheduled to be removed in Gradle 3.0. please use the official plugin from SonarQube (http://docs.sonarqube.org/display/SONAR/Analyzing+with+Gradle).
`

Which ironically points to a dead page - such a public link should at the very least redirect to the new location.

**Comment by ajoberstar** [comment]
I'll take care of this in the next release. I've been more focused on other projects, so I don't know when that will be.
