### ISSUE TITLE
Support for testing changes locally

### ISSUE THREAD

**Issue by eaaltonen** [ajoberstar/gradle-defaults#18]
I just forked the `grgit-plugin` to see if I need to change anything to support my use case (on going).

I want to test the changes locally with
```
gritgit$ gradle publishToMavenLocal
my-project$ gradle
```

The jar in the local Maven repository does not however have a `META-INF/gradle-plugins/` properties file, making it difficult to test the changes locally. I just get an

    Plugin with id 'org.ajoberstar.grgit' not found.

**Comment by ajoberstar** [comment]
Please reopen your issue on [gradle-git](https://github.com/ajoberstar/gradle-git). This will make it easier for others to find in the future if they have the same issue. Thanks!
